import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-neutral-50 text-neutral-900">
        <header className="border-b bg-white">
          <div className="mx-auto max-w-4xl p-4 flex justify-between items-center">
            <div className="font-semibold">Campaign Dashboard</div>
            <nav>
              <Link href="/campaigns" className="text-sm underline">
                  Campaigns
              </Link>
            </nav>
          </div>
        </header>

        <div className="mx-auto max-w-4xl">
          {children}
        </div>
      </body>
    </html>
  );
}
